name: Create an adaptation PR

# This action was renamed to `adaptation-pr-create`. This is a thin wrapper that
# forwards to the new action, kept for backwards compatibility.

inputs:
  app-token:
    description: GitHub app token.
    required: true

  app-slug:
    description: GitHub app slug.
    required: true

  upstream-pr:
    description: >
      The upstream PR number to create the adaptation PR for.
    required: true

  upstream-ci-green:
    description: >
      Whether the upstream PR CI is considered green. If it is not green, the
      action will not attempt to create an adaptation PR.
    default: true

  upstream-branch:
    description: >
      Branch in the upstream repo that marks the latest commit with green
      downstream CI.
    default: downstream-green

  upstream-label:
    description: >
      Label to add to an upstream PR to trigger adaptation PR creation.
    default: downstream

  downstream-repo:
    description: >
      The downstream repository to search for adaptation PRs and dispatch the
      downstream action in, in "owner/repo" format.
    required: true

  downstream-clone:
    description: >
      Path to a (potentially treeless) clone of the downstream repository.
    required: true

  downstream-branch:
    description: >
      The branch in the downstream repo to create the adaptation PR against.
    default: green

  downstream-label:
    description: >
      Label to attach to all adaptation PRs created by this action.

  override-toolchain:
    description: >
      Override the toolchain in the adaptation PR with this value. If not set,
      the toolchain will not be modified.

runs:
  using: composite
  steps:
    - uses: ./actions/adaptation-pr-create
      with:
        app-token: ${{ inputs.app-token }}
        app-slug: ${{ inputs.app-slug }}
        upstream-pr: ${{ inputs.upstream-pr }}
        upstream-ci-green: ${{ inputs.upstream-ci-green }}
        upstream-branch: ${{ inputs.upstream-branch }}
        upstream-label: ${{ inputs.upstream-label }}
        downstream-repo: ${{ inputs.downstream-repo }}
        downstream-clone: ${{ inputs.downstream-clone }}
        downstream-branch: ${{ inputs.downstream-branch }}
        downstream-label: ${{ inputs.downstream-label }}
        override-toolchain: ${{ inputs.override-toolchain }}
